const MONGODB_URI = process.env.MONGODB_URI;
const PORT = process.env.PORT;
const ACCESS_SECRET_KEY = process.env.ACCESS_SECRET_KEY;
const REFRESH_SECRET_KEY = process.env.REFRESH_SECRET_KEY;

export { MONGODB_URI, PORT, ACCESS_SECRET_KEY, REFRESH_SECRET_KEY };
